my_string=input('Как вас зовут? ')
my_string=input('Как вас зовут? '. upper())
my_string=input('Как вас зовут? '.lower())
my_string=input('Как вас зовут? '.replace(' ', ''))
my_string=input('Как вас зовут? '.replace('Как вас зовут?', 'К'))
my_string=input('Как вас зовут? '.replace('Как вас зовут?', '?'))